# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"x\n\rSensorReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x12\n\nts_unix_ms\x18\x02 \x01(\x03\x12\x0c\n\x04site\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x01\x12\x10\n\x08humidity\x18\x05 \x01(\x01\x12\x0b\n\x03seq\x18\x06 \x01(\x04\"\x1d\n\tIngestAck\x12\x10\n\x08last_seq\x18\x01 \x01(\x04\"C\n\x0cQueryRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\x03\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\x03\"G\n\nQueryPoint\x12\x12\n\nts_unix_ms\x18\x01 \x01(\x03\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x10\n\x08humidity\x18\x03 \x01(\x01\"3\n\nQueryReply\x12%\n\x06points\x18\x01 \x03(\x0b\x32\x15.telemetry.QueryPoint\"1\n\x0eMetricsRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04site\x18\x02 \x01(\t\"x\n\x06Metric\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04site\x18\x02 \x01(\t\x12\x11\n\twindow_ms\x18\x03 \x01(\x03\x12\x10\n\x08\x61vg_temp\x18\x04 \x01(\x01\x12\x14\n\x0c\x61vg_humidity\x18\x05 \x01(\x01\x12\x12\n\nts_unix_ms\x18\x06 \x01(\x03\"/\n\x0c\x41lertRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04site\x18\x02 \x01(\t\"n\n\x05\x41lert\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04site\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x11\n\tthreshold\x18\x05 \x01(\x01\x12\x12\n\nts_unix_ms\x18\x06 \x01(\x03\x32O\n\tIngestion\x12\x42\n\x0eStreamReadings\x12\x18.telemetry.SensorReading\x1a\x14.telemetry.IngestAck(\x01\x32\x43\n\x08QueryAPI\x12\x37\n\x05Range\x12\x17.telemetry.QueryRequest\x1a\x15.telemetry.QueryReply2P\n\nAggregator\x12\x42\n\x10SubscribeMetrics\x12\x19.telemetry.MetricsRequest\x1a\x11.telemetry.Metric0\x01\x32I\n\x07\x41lerter\x12>\n\x0fSubscribeAlerts\x12\x17.telemetry.AlertRequest\x1a\x10.telemetry.Alert0\x01\x42\x39Z7github.com/Abdullah007noman/My-Distributed-System/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/Abdullah007noman/My-Distributed-System/proto'
  _globals['_SENSORREADING']._serialized_start=30
  _globals['_SENSORREADING']._serialized_end=150
  _globals['_INGESTACK']._serialized_start=152
  _globals['_INGESTACK']._serialized_end=181
  _globals['_QUERYREQUEST']._serialized_start=183
  _globals['_QUERYREQUEST']._serialized_end=250
  _globals['_QUERYPOINT']._serialized_start=252
  _globals['_QUERYPOINT']._serialized_end=323
  _globals['_QUERYREPLY']._serialized_start=325
  _globals['_QUERYREPLY']._serialized_end=376
  _globals['_METRICSREQUEST']._serialized_start=378
  _globals['_METRICSREQUEST']._serialized_end=427
  _globals['_METRIC']._serialized_start=429
  _globals['_METRIC']._serialized_end=549
  _globals['_ALERTREQUEST']._serialized_start=551
  _globals['_ALERTREQUEST']._serialized_end=598
  _globals['_ALERT']._serialized_start=600
  _globals['_ALERT']._serialized_end=710
  _globals['_INGESTION']._serialized_start=712
  _globals['_INGESTION']._serialized_end=791
  _globals['_QUERYAPI']._serialized_start=793
  _globals['_QUERYAPI']._serialized_end=860
  _globals['_AGGREGATOR']._serialized_start=862
  _globals['_AGGREGATOR']._serialized_end=942
  _globals['_ALERTER']._serialized_start=944
  _globals['_ALERTER']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
